directories:
  output: dist
  buildResources: build
appId: com.evoke.tj
productName: TJ Neuralink 1.0.1
win:
  target: nsis
  icon: resources/icon.ico
extraResources:
  - from: resources/ollama
    to: ollama
    filter:
      - '**/*'
  - from: resources/models
    to: models
    filter:
      - '**/*'
files:
  - filter:
      - main.js
      - preload.js
      - index.html
      - style.css
      - renderer.js
      - character.md
electronVersion: 31.7.7
